### ISSUE TITLE
Non constant operand of OpSpecConstantOp 

### ISSUE THREAD

**Issue by kkyzylov** [KhronosGroup/SPIRV-Headers#12]
SPIR-V translator generates OpSpecConstantOp instruction with non-const operand, which violates spec requirements for this instruciton:
> Operands are the operands required by opcode, and satisfy the semantics of opcode. In addition, all Operands must be the <id>s of other constant instructions.

`%11 = OpSpecConstantOp %10 InBoundsPtrAccessChain %8 %9 %9`
`%8 = OpVariable %7 CrossWorkgroup %6`

OpVariable is not a constant instruction.

LLVM code contains  ConstantExpr with GlobalVariable as first operand.

`@v = addrspace(1) global [2 x i32] [i32 1, i32 2], align 4`
`@s = addrspace(1) global i32 addrspace(1)* getelementptr inbounds ([2 x i32] addrspace(1)* @v, i32 0, i32 0), align 4`

 In this case there is no way to satisfy the the semantics of OpSpecConstantOp instruction.

[OpSpecConstantOp.ll.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/323542/OpSpecConstantOp.ll.txt)
[OpSpecConstantOp.spt.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/323543/OpSpecConstantOp.spt.txt)
[OpSpecConstantOp.spv.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/323544/OpSpecConstantOp.spv.txt)
[OpSpecConstantOp.cl.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/323545/OpSpecConstantOp.cl.txt)

**Comment by dneto0** [comment]
I see what you're saying.
In LLVM it's very clear that a global value (such as @v in your case) is a constant in the IR.  Its value (an address) is known by the time the program starts.

In SPIR-V, no OpVariable is deemed to be constant, not even in CrossWorkgroup storage class.  So that "v" variable is not deemed to be a value you can use in the OpSpecConstantOp InBoundsAccessChain  instruction.  
In fact, passing the current SPIR-V Validator rejects the module with a use-before-definition error:
```
error: 23: ID 2[v] has not been defined
```

I'll take this to the SPIR Working Group for discussion.

**Comment by johnkslang** [comment]
Khronos has decided on OpVariable can be treated as constant for this purpose, and that will be reflected in revision 6 of 1.0 and revision 2 of 1.1.
