### ISSUE TITLE
OpPtrAccessChain/OpPtrDiff elimination

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/SPIRV-Headers#161]
Perhaps this is the wrong place to post this question, but are there LLVM passes or a theory of CFG transforms to help reduce out OpPtrAccessChain and OpPtrDiff and replace them with Logical-addressing compatible instructions? I'm trying to lower C++ to SPIRV.

```cpp
float array[5];
float* p = array;
p[3] = 10;
```

The array->pointer uses the OpAccessChain, which has to be basically dragged down to where the OpPtrAccessChain is:
```
%array = OpVariable float[5], Function
%p = OpAccessChain %array, 0
%p2 = OpPtrAccessChain %p, 3
OpStore %p2, 10
   transform to:
%p2 = OpAccessChain %array, 3
OpStore %p2, 10
```

The hoisting is easy with linear control flow, but back edges and nesting etc make it a challenge. And replacing OpPtrDiff is quite difficult, requiring finding the greatest common OpAccessChain between the two operands then computing linear offsets from those instructions forward. Are there theories or papers to help me through this?

**Comment by johnkslang** [comment]
With this not being an issue against the headers, there is probably a better place.  The SPIRV-Tools project would have more expertise overlapping this area, but still it is not an issue really against SPIRV-Tools, unless a request/attempt to add a transform for removing these.

Maybe https://community.khronos.org/ is the best place.

You already seem aware that within SPIR-V, logical addressing does not allow OpPtrAccessChain or OpPtrDiff, unless also using a VariablePointers capability.  So, presumably you have a tool chain generating these even when you don't want them to.  Detailing that in an issue might help.  OpPtrDiff would hopefully never be created when targeting logical addressing, because it implies somehow crossing a line from array indexes being numerical addresses that take into account the number of bytes needed to store elements, and then wanting to do arithmetic in that space, which is inconsistent with logical addressing.  Logical addressing should remain in the "index" space, and then OpPtrDiff is just "index diff".  One clue I can offer: Older versions of LLVM stayed better behaved (more logical) when not being given any target data.  I haven't checked more recent versions.
