### ISSUE TITLE
SPIRV-Headers commit (renaming constants) broke Vulkan-ValidationLayers compile

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/SPIRV-Headers#365]
https://github.com/KhronosGroup/SPIRV-Headers/commit/272be321ad6ccb8bc7533c325a5faf5806e6c06f#commitcomment-122986045

**Comment by romanl-g** [comment]
Very sad that there is no CI checks for this

**Comment by kpet** [comment]
Sorry for this, we knew this was going to be a breaking change and that's why we've made it as soon as the need was spotted. You will need to follow the name change. Let us know if there's anything we can do to help or if you find an issue with the change itself.

**Comment by romanl-g** [comment]
Both of these repos are under `KhronosGroup/`, my assumption was that some communication could happen there without external parties

**Comment by Tobski** [comment]
Hi @romanl-g, the Validation layers (and all of our other tools) pointedly make use of a specific tagged version of all the dependency repos that it uses so that changes in one repo (e.g. this one) don't break anything until they're properly integrated. Validation layers aren't expected to work with the most up to date version of each dependency for reasons explicitly like this; any change could hypothetically break other tools. So our communication chain is handled by propagating the versions in turn and fixing any issues before updating the version.

If it's not clear from the Validation layers that they are not expected to work with every one of the latest commits, it might be worth raising an issue there to ask to make this clearer or perhaps automatically verify this during a build?

**Comment by dneto0** [comment]
@Tobski is right.  The communication is happening in the background, not explicitly in public view. 

The Vulkan SDK pulls together all the pieces and has extensive quality checks to make sure it works reasonably well. This happens roughly every 6 weeks.
If you want to build things yourself, I recommend taking the set of commits as published in each new Vulkan SDK release.

**Comment by romanl-g** [comment]
My point was that VVL could've been informed at the same time (or ideally before..) as the breaking commit.
Like what I did here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6225

When we ran into this issue I actually didn't know that VVL depended on a specific commit here.
Another bit of history I was missing is that ANGLE previously did check out the vulkan-headers version referenced by VVL, but then had to switch to ToT because it wasn't reliable (VVL would lag behind without a particular reason it seems).

Either way, it looks like we're spending time working around `KhronosGroup/` repos going out of sync one way or another which seems counter-productive.

**Comment by romanl-g** [comment]
Regarding communication happening in background, I think confusion here is an indicator that something is still missing: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6225#issuecomment-1659567318

**Comment by Tobski** [comment]
We fairly routinely break minor things between the repos, which is why we have a set update schedule, and why nobody was informed outside of that schedule. If something needs major work, we'll give a heads up in advance, but this would've generally been caught without fanfare the next time VVL did such an update.

**Comment by bashbaug** [comment]
Thanks for raising this issue.  To summarize, we recommend taking a set of commits that are known to work well together if you would like to build things yourself.  If you try to build with top-of-tree, things will usually work, but occasionally we'll be out-of-sync and things will break.  When this happens we'll try to fix things quickly, certainly before the next release.

Since discussion seems to have slowed and I don't believe any additional action is required I am closing this issue - thanks again!
