### ISSUE TITLE
Clarification on code motion section

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Headers#58]
> Texturing instructions in the Fragment Execution Model that rely on an implicit derivative cannot be moved into control flow that is not known to be uniform control flow within each derivative group.

It's not totally clear to me what `cannot be moved` means in this context. Is it not allowed to have texture ops with implicit derivatives to be inside non-uniform control flow paths? Compilers should not move those instructions into non-uniform control flow paths?

**Comment by dneto0** [comment]
Section 2.19 "Derivatives" says 
"In all cases, derivatives are well defined only if the derivative group has uniform control flow."

So:
 
> Is it not allowed to have texture ops with implicit derivatives to be inside non-uniform control flow paths? 

Correct.

> Compilers should not move those instructions into non-uniform control flow paths?

Correct.

I see that it could be confusing to talk about what a compiler does.  Sometimes it's better for a spec to *only* describe the meaning of an unchanging module.

Does this answer your question?

**Comment by cforfang** [comment]
It doesn't quite follow for me that derivatives not being well defined inside non-uniform control flow should result in straight-up invalid SPIR-V in this case. For example, if an image only has 1 mip-level it doesn't matter if the derivatives aren't well defined since they won't be needed.

On the other hand, it makes sense to me to make it explicit _the compiler_ shouldn't move texture ops from inside to outside uniform control flow, because this obviously changes the behavior of the texture op (as derivatives change from well-defined to undefined). But if the shader author has already placed it inside non-uniform flow, knowing this is OK (like the 1 mip level case above), that seems like it should be fine?

(Another side of this is I'm not sure it's possible to _prove_ what's uniform and non-uniform control flow statically, so valid/invalid SPIR-V might all be semantics here. :) In practice I believe the texture ops should work on all hardware, even if it might not do what you want if you rely on well-defined derivatives.)

**Comment by msiglreith** [comment]
@dneto0 Thanks, that answers my question (:

**Comment by ratchetfreak** [comment]
> (Another side of this is I'm not sure it's possible to prove what's uniform and non-uniform control flow statically, so valid/invalid SPIR-V might all be semantics here. :)

actually it is. but it's the kind of description filled with caveats. from the spec:

> Uniform Control Flow: Uniform control flow (or converged control flow) occurs when all invocations in the invocation group or derivative group execute the same control-flow path (and hence the same sequence of dynamic instances of instructions). Uniform control flow is the initial state at the entry point, and lasts until a conditional branch takes different control paths for different invocations (non-uniform or divergent control flow). Such divergence can reconverge, with all the invocations once again executing the same control-flow path, and this re-establishes the existence of uniform control flow. If control flow is uniform upon entry into a header block, and all invocations leave that dynamic instance of the header block’s control-flow construct via the header block’s declared merge block, then control flow reconverges to be uniform at that merge block.

so a OpBranchConditional or OpSwitch are the only instructions that can diverse control flow from uniform but not if the condition or selector are derived only from uniform data. And if a one of them diverges control flow then  control flow will reconvene to uniform in its mergeblock.

Whether data is uniform can be achieved using a propagating tag algorithm, some results are always non-uniform (like loads from non-flat inputs) and every instruction that uses that result will also give a non-uniform result. The result of an opPhi is uniform iff all values used are uniform and control flow to from each preceding block is uniform.

**Comment by johnkslang** [comment]
Closing, since the original poster said the question was answered.
