### ISSUE TITLE
Merge SPIRV directory in glslang into SPIRV-Headers repo

### ISSUE THREAD

**Issue by rafaga** [KhronosGroup/SPIRV-Headers#97]
Checking SPIRV-Headers and SPIRV directory in glslang I see both are the almost the same headers.
I notice that glslang build the libSPIRV static library and is using an old version of th SPIRV headers compared with this repo.

Could be considered a merge Between SPIRV C++ Files in glslang and the Headers present in this repo? 

Doing this move It would help to create a libspirv library version that always be up-to-date. I'm making a Homebrew formula can be used to compile MoltenVK and helps the developers, and considering this merge would ease the task of keeping libSPIRV library and the SPIRV-headers up-to-date and unified.

**Comment by johnkslang** [comment]
Yes, currently this repository leads others repositories as new features show up. We'd want a way to test glslang when updating here, so that an update here would not immediately break glslang. I know some were working on a more unified system, but am not sure of status at the moment.

Still, the headers should never be inconsistent with each other, and the official header comes from this repository, not what glslang has.

**Comment by johnkslang** [comment]
Glslang has been updated to the latest headers. They should match now.

**Comment by johnkslang** [comment]
If there is any issue still remaining here, I think it is against glslang, not this repository.

**Comment by rafaga** [comment]
Ok thanks and i will submit in glslang repo the remaining issues. Thank you.
